#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
//#include "MGameTypes.generated.h"

CUTSCENEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MENU);
CUTSCENEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME_MENU);
CUTSCENEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME);
CUTSCENEPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MODAL);
